
/**
 * Lignes
 */
export const  FETCH_BUS_LIGNES_REQUEST = 'FETCH_BUS_LIGNES_REQUEST';
export const  FETCH_BUS_LIGNES_SUCCESS = 'FETCH_BUS_LIGNES_SUCCESS';
export const  FETCH_BUS_LIGNES_FAILURE = 'FETCH_BUS_LIGNES_FAILURE';

/**
 * reservation bus
 */
export const  FETCH_BUS_RESERVATION_REQUEST = 'FETCH_BUS_RESERVATION_REQUEST';
export const  FETCH_BUS_RESERVATION_SUCCESS = 'FETCH_BUS_RESERVATION_SUCCESS';
export const  FETCH_BUS_RESERVATION_FAILURE = 'FETCH_BUS_RESERVATION_FAILURE';

/**
 * liste menus
 */
export const  FETCH_MENU_LIST_REQUEST = 'FETCH_MENU_LIST_REQUEST';
export const  FETCH_MENU_LIST_SUCCESS = 'FETCH_MENU_LIST_SUCCESS';
export const  FETCH_MENU_LIST_FAILURE = 'FETCH_MENU_LIST_FAILURE';

/**
 * login
 */
export const  FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const  FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const  FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

/**
 * client
 */
export const  FETCH_CLIENT_REQUEST = 'FETCH_CLIENT_REQUEST';
export const  FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const  FETCH_CLIENT_FAILURE = 'FETCH_CLIENT_FAILURE';

/**
 * plat 
 */
export const  AJOUT_PLAT = 'AJOUT_PLAT';
export const  RETRAIT_PLAT = 'RETRAIT_PLAT';

export const LOG_OUT = 'LOG_OUT';