
/**
 * Lignes
 */
export const  FETCH_BUS_LIGNES_REQUEST = 'FETCH_BUS_LIGNES_REQUEST';
export const  FETCH_BUS_LIGNES_SUCCESS = 'FETCH_BUS_LIGNES_SUCCESS';
export const  FETCH_BUS_LIGNES_FAILURE = 'FETCH_BUS_LIGNES_FAILURE';

/**
 * reservation bus
 */
export const  FETCH_BUS_RESERVATION_REQUEST = 'FETCH_BUS_RESERVATION_REQUEST';
export const  FETCH_BUS_RESERVATION_SUCCESS = 'FETCH_BUS_RESERVATION_SUCCESS';
export const  FETCH_BUS_RESERVATION_FAILURE = 'FETCH_BUS_RESERVATION_FAILURE';
/**
 * historique bus
 */
export const  FETCH_BUS_RESERVATION_HISTO_REQUEST = 'FETCH_BUS_RESERVATION_HISTO_REQUEST';
export const  FETCH_BUS_RESERVATION_HISTO_SUCCESS = 'FETCH_BUS_RESERVATION_HISTO_SUCCESS';
export const  FETCH_BUS_RESERVATION_HISTO_FAILURE = 'FETCH_BUS_RESERVATION_HISTO_FAILURE';
export const  SET_RESERVATION_STATUS_FALSE = 'SET_RESERVATION_STATUS_FALSE';
export const  SET_RENEW_ERROR_STATUS = 'SET_RENEW_ERROR_STATUS';

/**
 * liste menus
 */
export const  FETCH_MENU_LIST_REQUEST = 'FETCH_MENU_LIST_REQUEST';
export const  FETCH_MENU_LIST_SUCCESS = 'FETCH_MENU_LIST_SUCCESS';
export const  FETCH_MENU_LIST_FAILURE = 'FETCH_MENU_LIST_FAILURE';

/**
 * login
 */
export const  FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const  FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const  FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

/**
 * client
 */
export const  FETCH_CLIENT_REQUEST = 'FETCH_CLIENT_REQUEST';
export const  FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const  FETCH_CLIENT_FAILURE = 'FETCH_CLIENT_FAILURE';


/**
 * reservationplat
 */
export const  FETCH_RESERVATIONPLAT_REQUEST = 'FETCH_RESERVATIONPLAT_REQUEST';
export const  FETCH_RESERVATIONPLAT_SUCCESS = 'FETCH_RESERVATIONPLAT_SUCCESS';
export const  FETCH_RESERVATIONPLAT_FAILURE = 'FETCH_RESERVATIONPLAT_FAILURE';


/**
 * InsertionPanier
 */
export const  INSERT_PANIER_REQUEST = 'INSERT_PANIER_REQUEST';
export const  INSERT_PANIER_SUCCESS = 'INSERT_PANIER_SUCCESS';
export const  INSERT_PANIER_FAILURE = 'INSERT_PANIER_FAILURE';

/**
 * creationReservation
 */
export const  CREATION_RESERVATION_REQUEST = 'CREATION_RESERVATION_REQUEST';
export const  CREATION_RESERVATION_SUCCESS = 'CREATION_RESERVATION_SUCCESS';
export const  CREATION_RESERVATION_FAILURE = 'CREATION_RESERVATION_FAILURE';

export const CLEAR_OLD_RESERVATION_DATA = 'CLEAR_OLD_RESERVATION_DATA';
export const SET_RESERVATION_PLAT_STATUS = 'SET_RESERVATION_PLAT_STATUS';

/**
 * plat 
 */
export const  AJOUT_PLAT = 'AJOUT_PLAT';
export const  RETRAIT_PLAT = 'RETRAIT_PLAT';
export const  AJOUT_QUANT = 'AJOUT_QUANT';
export const  RETRAIT_QUANT = 'RETRAIT_QUANT';

export const LOG_OUT = 'LOG_OUT';

/**
 * histo reservation
 */

 export const FETCH_HISTO_RESERVATION_REQUEST = 'FETCH_HISTO_RESERVATION_REQUEST';
 export const FETCH_HISTO_RESERVATION_SUCCESS = 'FETCH_HISTO_RESERVATION_SUCCESS';
 export const FETCH_HISTO_RESERVATION_FAILURE = 'FETCH_HISTO_RESERVATION_FAILURE';


 /**
  * inscription
  */

  export const FETCH_SIGNUP_REQUEST = 'FETCH_SIGNUP_REQUEST';
  export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
  export const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE';
  export const SET_SIGNUP_STATUS = 'SET_SIGNUP_STATUS';